import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Link from 'next/link';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <aside className="h-screen w-40">
          <nav className="h-full flex flex-col bg-amber-200 border-r shadow-sm">
            <div className="p-4 pb-2 flex justify-between items-center">
              <Link href="/account">Account</Link>
            </div>
            <div className="p-4 pb-2 flex justify-between items-center">
              <Link href="/dashboard">Dashboard</Link>
            </div>
            <div className="p-4 pb-2 flex justify-between items-center">
              <Link href="/calendar">Calendar</Link>
            </div>
            <div className="p-4 pb-2 flex justify-between items-center">
              <Link href="inbox">Inbox</Link>
            </div>
          </nav>
        </aside>

        <main className="flex-1 p-8 items-center justify-items-center min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
